version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  myfirstenv:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo First_Env_Var
workflows:
  welcome:
    jobs:
      - say-hello
      - print-world
      - myfirstenv
     

        
          
         
